// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResourcehubApiDotNet.Models;

namespace ResourcehubApiDotNet.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200410054851_UserOAuth")]
    partial class UserOAuth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ResourcehubApiDotNet.Models.OAuthTwitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("accessToken")
                        .HasColumnType("text");

                    b.Property<string>("accessTokenSecret")
                        .HasColumnType("text");

                    b.Property<string>("platformAvatar")
                        .HasColumnType("text");

                    b.Property<int>("platformUserId")
                        .HasColumnType("integer");

                    b.Property<string>("platformUsername")
                        .HasColumnType("text");

                    b.Property<string>("usernameFK")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OAuthTwitter");
                });

            modelBuilder.Entity("ResourcehubApiDotNet.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("primaryOauthProvider")
                        .HasColumnType("text");

                    b.HasKey("username");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
